services:
    vpn-bot:
        build: .
        container_name: vpn-bot
        restart: always
        env_file:
            - .env
        volumes:
            - vpn-bot-data:/app/data

volumes:
    vpn-bot-data:
        driver: local
